require:
  - standard/cop/block_single_line_braces
  - ruby-next/rubocop

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "Gemfile"
    - "vendor/**/*"
    - "gemfiles/**/*"
    - "*.gemspec"
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: next

Naming/FileName:
  Exclude:
    - "**/*.md"

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashConversion:
  Enabled: false

Style/EndlessMethod:
  EnforcedStyle: allow_always

Layout/SpaceAfterColon:
  Enabled: false

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Lint/ConstantDefinitionInBlock:
  Enabled: false
