name: Lint Ruby

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler: 2.2.15
        bundler-cache: true
    - name: Lint Rubocop
      run: |
        bundle exec rake rubocop:all